    steps:
            - uses: actions/checkout@v4
            - name: arduino/arduino-lint-action
            - uses: arduino/arduino-lint-action@v1.0.2
        with:
          library-manager: update
          compliance: strict
