name: Arduino Lint

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: arduino/arduino-lint-action@v1.0.2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification
          library-manager: update
          # Always use this setting for official repositories. Remove for 3rd party projects.
          project-type: library
